apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-alert-data
  namespace: k8s-app
  labels:
    app: opensearch-alert
    version: "v3.5.0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi