name: 应用Pod错误日志告警
type: frequency
index: ks-whizard-logging-*
threshold: 10
timeframe: 300
query_key:
  - "@timestamp"
  - "involvedObject.name"
realert: 5
alert:
  - "email"
  - "dingtalk"
  - "wechat"
  - "feishu"
alert_text: ${kubernetes.pod_name} 出现错误
alert_text_args: []
level: High
enabled: true
query:
    bool:
        must:
            - bool:
                minimum_should_match: 1
                should:
                    - match:
                        log: ERROR
                    - match:
                        log: FATAL
                    - match:
                        log: Exception
                    - match:
                        log: stacktrace
                    - match:
                        log: panic
        must_not:
            - match:
                log: INFO
            - match:
                kubernetes.container_name: dockerd
            - match:
                kubernetes.container_name: kubelet
            - match:
                kubernetes.container_name: kube-apiserver
            - match:
                kubernetes.container_name: kube-controller-manager
            - match:
                kubernetes.container_name: kube-scheduler
            - match:
                kubernetes.container_name: kube-proxy
            - match:
                kubernetes.container_name: coredns
            - match:
                kubernetes.container_name: etcd
            - match:
                kubernetes.container_name: calico-node
            - match:
                kubernetes.container_name: calico-kube-controllers
            - match:
                kubernetes.container_name: prometheus
            - match:
                kubernetes.container_name: grafana
            - match:
                kubernetes.container_name: ks-controller-manager
            - match:
                kubernetes.container_name: ks-apiserver
            - match:
                kubernetes.container_name: ks-console
            - match:
                kubernetes.container_name: scope-agent
            - match:
                kubernetes.container_name: fluent-bit
            - match:
                kubernetes.container_name: log-simulator
