name: "系统组件错误日志告警"
type: "frequency"
index: "ks-whizard-logging-*"
threshold: 50
timeframe: 300
query_key:
  - "@timestamp"
  - "log"
realert: 5
alert:
  - "email"
  - "dingtalk"
  - "wechat"
  - "feishu"
alert_text: "系统组件出现错误日志"
level: "Critical"
enabled: true
query:
  bool:
    must:
      - bool:
          should:
            - match:
                log: "ERROR"
            - match:
                log: "FATAL"
            - match:
                log: "Exception"
            - match:
                log: "stacktrace"
            - match:
                log: "panic"
          minimum_should_match: 1
      - bool:
          should:
            - term:
                "kubernetes.container_name": "dockerd"
            - term:
                "kubernetes.container_name": "kubelet"
            - term:
                "kubernetes.container_name": "kube-apiserver"
            - term:
                "kubernetes.container_name": "kube-controller-manager"
            - term:
                "kubernetes.container_name": "kube-scheduler"
            - term:
                "kubernetes.container_name": "kube-proxy"
            - term:
                "kubernetes.container_name": "coredns"
            - term:
                "kubernetes.container_name": "etcd"
            - term:
                "kubernetes.container_name": "calico-node"
            - term:
                "kubernetes.container_name": "calico-kube-controllers"
            - term:
                "kubernetes.container_name": "prometheus"
            - term:
                "kubernetes.container_name": "grafana"
            - term:
                "kubernetes.container_name": "ks-controller-manager"
            - term:
                "kubernetes.container_name": "ks-apiserver"
            - term:
                "kubernetes.container_name": "ks-console"
            - term:
                "kubernetes.container_name": "scope-agent"
          minimum_should_match: 1
    must_not:
      - match:
          log: "INFO"


