# 安全事件告警规则
# 监控Kubernetes安全审计事件，包括敏感资源操作、权限变更等
name: "安全审计告警"                # 规则名称，用于标识和显示
type: "any"                       # 规则类型：any（任意型，匹配到即触发）
index: "ks-whizard-auditing-*"    # 监控的OpenSearch索引模式
threshold: 1                      # 触发阈值：匹配1条记录即触发告警
timeframe: 60                     # 时间窗口：1分钟内
query_key:                        # 查询键，用于去重和分组
  - "@timestamp"                  # 时间戳字段
  - "AuditID"                     # 审计ID字段
realert: 0                        # 重复告警间隔：0分钟（立即告警）
alert:                            # 启用的通知渠道
  - "email"                       # 邮件通知
  - "dingtalk"                    # 钉钉通知
  - "wechat"                      # 企业微信通知
  - "feishu"                      # 飞书通知
alert_text: "检测到安全相关操作"    # 告警文本描述
level: "Critical"                 # 告警级别：严重，会@用户
enabled: true                     # 是否启用此规则
query:
  bool:
    must:
      - bool:
          should:
            - term:
                Level: "Error"
            - term:
                Verb: "delete"
            - term:
                Verb: "create"
            - term:
                Verb: "update"
          minimum_should_match: 1
      - bool:
          should:
            - term:
                "ObjectRef.Resource": "secrets"
            - term:
                "ObjectRef.Resource": "configmaps"
            - term:
                "ObjectRef.Resource": "roles"
            - term:
                "ObjectRef.Resource": "rolebindings"
          minimum_should_match: 1
