name: 应用Pod警告日志告警
type: frequency
index: ks-whizard-logging-*
threshold: 10
timeframe: 300
query_key:
    - '@timestamp'
    - log
realert: 10
alert:
    - email
    - dingtalk
    - wechat
    - feishu
alert_text: 应用Pod出现警告日志
alert_text_args: []
level: Medium
enabled: true
query:
    bool:
        must:
            - bool:
                minimum_should_match: 1
                should:
                    - match:
                        log: WARN
                    - match:
                        log: WARNING
        must_not:
            - match:
                log: INFO
            - match:
                log: ERROR
            - match:
                log: FATAL
            - match:
                kubernetes.container_name: dockerd
            - match:
                kubernetes.container_name: kubelet
            - match:
                kubernetes.container_name: kube-apiserver
            - match:
                kubernetes.container_name: kube-controller-manager
            - match:
                kubernetes.container_name: kube-scheduler
            - match:
                kubernetes.container_name: kube-proxy
            - match:
                kubernetes.container_name: coredns
            - match:
                kubernetes.container_name: etcd
            - match:
                kubernetes.container_name: calico-node
            - match:
                kubernetes.container_name: calico-kube-controllers
            - match:
                kubernetes.container_name: prometheus
            - match:
                kubernetes.container_name: grafana
            - match:
                kubernetes.container_name: ks-controller-manager
            - match:
                kubernetes.container_name: ks-apiserver
            - match:
                kubernetes.container_name: ks-console
            - match:
                kubernetes.container_name: scope-agent
            - match:
                kubernetes.container_name: fluent-bit
