opensearch:
    host: 192.168.233.246
    port: 31469
    protocol: https
    username: admin
    password: admin
    verify_certs: false
    timeout: 30
alert_engine:
    run_interval: 60
    buffer_time: 300
    max_running_rules: 10
    writeback_index: opensearch_alert_status
    alert_time_limit: 172800
alert_suppression:
    enabled: true
    realert_minutes: 2
    exponential_realert:
        enabled: false
        hours: 1
notifications:
    email:
        enabled: false
        smtp_server: smtp.qq.com
        smtp_port: 587
        username: 2099637909@qq.com
        password: xxxxxxxxxxxxxxxxxxxx
        from_email: 2099637909@qq.com
        to_emails: [2099637909@qq.com]
        use_tls: true
    dingtalk:
        enabled: false
        webhook_url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxx
        secret: xxxxxxxxxxxxxxxxxxx
        at_mobiles:
            - "1833282xxxx"
        at_all: false
    wechat:
        enabled: false
        webhook_url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxx
        mentioned_list: []
        mentioned_mobile_list:
            - "1833282xxxx"
        at_all: false
    feishu:
        enabled: true
        webhook_url: https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxxxxxxxxxxxxxx
        secret: ""
        at_mobiles: []
        at_all: true
logging:
    level: INFO
    format: 2006-01-02 15:04:05 - %s - %s - %s
    file: logs/opensearch-alert/alert.log
    max_size: 10MB
    backup_count: 5
web:
    enabled: true
    host: 0.0.0.0
    port: 8080
    static_path: web/static
    template_path: web/templates
    session_secret: opensearch-alert-secret-key-2024
database:
    type: mysql
    path: data/opensearch-alert.db
    max_connections: 50
    max_idle_connections: 5
    host: 192.168.233.246
    port: 32529
    username: opensearch_alert
    password: opensearch_alert
    dbname: opensearch_alert
    params: charset=utf8mb4&parseTime=true&loc=Local
auth:
    enabled: true
    session_timeout: 3600
    users:
        - username: admin
          password: TianXiang2099637909!@#
          role: admin
        - username: viewer
          password: viewer123
          role: viewer
rules:
    rules_folder: configs/rules
    default_timeframe: 300
    default_threshold: 1
